CI: Skip Haddock gen for GHC 8.0.2 and 8.2.2

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -73,7 +73,15 @@ jobs:
       run: cabal build --enable-tests --enable-benchmarks all
 
     - name: Test Haddock generation
-      run: cabal v2-haddock --enable-documentation
+      run: |
+        # For earlier versions this error appears:
+        # “cabal: Failed to build documentation for vector-0.13.0.0
+        # (which is required by qm-interpolated-string-0.3.1.0).”
+        if [[ ${{ matrix.ghc }} != 8.0.2 && ${{ matrix.ghc }} != 8.2.2 ]]; then
+          cabal v2-haddock --enable-documentation
+        else
+          >&2 echo Skipping...
+        fi
 
     - name: Run tests
       run: cabal test all
